[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = "full"
opt-level = 0

[profile.test]
inherits = "dev"

[dependencies]
proc_macros = { path = "proc_macros" }
regex = "1.11.1"
nom = "7.1.3"
reqwest = { version = "0.11.27", features = ["blocking", "json"] }