[package]
name = "proc_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
proc-macro2 = "*"
utils = {path = "../utils" }

[lib]
proc-macro = true